name: Laravel Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, bcmath, pdo, sqlite, mysql, openssl, tokenizer, xml, ctype, json, curl
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Prepare environment
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Create ZIP artifact
      run: zip -r laravel_app.zip . -x "*.git*"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: laravel_app
        path: laravel_app.zip
