name: Build Laravel App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo, pdo_mysql
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Prepare artifact (zip project + db.sql)
        run: |
          mkdir -p /tmp/build
          rsync -av --exclude='.git' --exclude='vendor' ./ /tmp/build/laravel_app
          cp db.sql /tmp/build/laravel_app/ || true
          cd /tmp/build
          zip -r laravel_app.zip laravel_app
          mv laravel_app.zip $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel_app
          path: laravel_app.zip
